travis:
  secure:
    BINSTAR_TOKEN: WFbzVEN1Sr8QhSNHce6iYwyhea/VIciv4Kee2g093IhpEwQx500aT1xgmHW6T5AH12StAcVi1UcUIqKU84REHOZZXEEHli/j6iCb3m7UW8m1NxsBbjZ7E2+5xbR5iAJIxt1P5etq5JvDRaY6Es8HhxQh3+2P9N2XKptWwFcmY0qUmYfcacb2rBsab+OPcJb/MVbRA2PG1QppXo+ANyPbZZw2DGeVCwDxEkI5sO4uwmXUqSKlctmwSJFhM2nd3Mh9WeOGhT0FicNpQDl2KuZ3Dz6jSmnQ9avdTTFFcq9PpnRFsjRIraZJirMHTeRsUtVJL/sb0hSMg6OmopAXj4U6iYE5TSLe4XNa9N5xQc+968l8OemOAUVvJJU5LLLx1gn69uOKEHlAaefd75hCqAfj4FtesMg3/8Md7QSeYuZfdsRpY8V9qBw5OUkbnFEHrfb5t1Pry5Jy12SHFEKIL+2zMmHD2VgZU/taSfjV/LRSWNu1cFoBOU6ELythT7psbfT18zNWOkbO16Z0a3YtNYlXkoT/0HO1k53kkqAd5JdoKE/Q/P0UlF2mNWu6teJYfpIOuAPdda76iML/JXHemXRN9TagyNz7pi2gq7C3jc5yg78694F8yBAw0qetAby1XZz48/qKlrJzxrEmcFYLHiXH/IwoeiDCTLsqBaXUz198dSg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
